### ISSUE TITLE
Login not working on Android - OnLoginStateChangedListener callbacks never called

### ISSUE THREAD

**Issue by alincatalin** [Snapchat/login-kit-sample#8]
I'm trying to do a Snapchat loking using the Login Kit on Android. I'm redirected to the Snapchat screen where I can grant the access - I'm redirected back to my activity but the OnLoginStateChangedListener is never called. 

I'm using `SnapLogin.getAuthTokenManager(this).startTokenGrant()` with the following scopes
```
    <string-array name="snap_connect_scopes">
        <item>https://auth.snapchat.com/oauth2/api/user.bitmoji.avatar</item>
        <item>https://auth.snapchat.com/oauth2/api/user.display_name</item>
    </string-array>
```

**Comment by gurkankesgin** [comment]
Are there any changes on the subject?

**Comment by CharlieZheng** [comment]
How you fix this issue? @alincatalin

**Comment by Mohamed1226** [comment]
the same error?
